language: php

php:
  - '7.3'
  - '7.4snapshot'

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./build/cc-test-reporter
  - chmod +x ./build/cc-test-reporter
  - ./build/cc-test-reporter before-build

install:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - vendor/bin/phing

script:
  - vendor/bin/phpcs -sp --report-junit=build/logs/phpcs.xml
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - ./build/cc-test-reporter after-build --id $CODECLIMATE_REPO_TOKEN --exit-code $TRAVIS_TEST_RESULT
